server:
  port: 8050
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO
zuul:
  ignoredServices: '*'
  routes:
    app-a:
      path: /user/**
      serviceId: consumer-feign-hystrix
    app-sidecar:                         #通过sidecar调用nodejs的服务
      path: /sidecar/**
      serviceId: sidecar